//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::Browser::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Browser::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            this->Tabs = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Tabs))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Browser::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Tabs_Click);
        }
        break;
    case 2:
        {
            this->Addressbar = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->Addressbar))->GotFocus += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Browser::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Addressbar_GotFocus);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->Addressbar))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Browser::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&MainPage::Addressbar_KeyDown);
        }
        break;
    case 3:
        {
            this->Menu = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Menu))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Browser::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Menu_Click);
        }
        break;
    case 4:
        {
            this->WebView = safe_cast<::Windows::UI::Xaml::Controls::WebView^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::WebView^>(this->WebView))->NavigationCompleted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewNavigationCompletedEventArgs^>(this, (void (::Browser::MainPage::*)
                (::Windows::UI::Xaml::Controls::WebView^, ::Windows::UI::Xaml::Controls::WebViewNavigationCompletedEventArgs^))&MainPage::WebView_FrameNavigationCompleted);
        }
        break;
    case 5:
        {
            this->BrowserProgress = safe_cast<::Windows::UI::Xaml::Controls::ProgressBar^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Browser::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


