#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ListView;
                ref class Grid;
                ref class Button;
                ref class TextBox;
                ref class ListViewItem;
                ref class WebView;
                ref class ProgressBar;
            }
        }
    }
}

namespace Browser
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::ListView^ PopupMenu;
        private: ::Windows::UI::Xaml::Controls::Grid^ QuickActionsMenu;
        private: ::Windows::UI::Xaml::Controls::Button^ Tabs;
        private: ::Windows::UI::Xaml::Controls::TextBox^ Addressbar;
        private: ::Windows::UI::Xaml::Controls::Button^ Menu;
        private: ::Windows::UI::Xaml::Controls::ListViewItem^ AboutBtn;
        private: ::Windows::UI::Xaml::Controls::WebView^ WebView;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ BrowserProgress;
    };
}

